//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooSungEngineering.LangResx {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WooSungEngineering.LangResx.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   적용되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyMsg {
            get {
                return ResourceManager.GetString("ApplyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   적용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyMsg1 {
            get {
                return ResourceManager.GetString("ApplyMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유량 1(L/min)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AxisY0 {
            get {
                return ResourceManager.GetString("AxisY0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압력 1(kg/cm²)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AxisY1 {
            get {
                return ResourceManager.GetString("AxisY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유량 2(L/min)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AxisY2 {
            get {
                return ResourceManager.GetString("AxisY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압력 2(kg/cm²)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AxisY3 {
            get {
                return ResourceManager.GetString("AxisY3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인쇄과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnPrintPDF {
            get {
                return ResourceManager.GetString("btnPrintPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChartAxisX {
            get {
                return ResourceManager.GetString("ChartAxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 기록들을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Delete2Msg {
            get {
                return ResourceManager.GetString("Delete2Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제하려는 기록이 조회중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteErrMsg {
            get {
                return ResourceManager.GetString("DeleteErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 기록을 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제 도중 오류가 발생하였습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteMsg_Err {
            get {
                return ResourceManager.GetString("DeleteMsg_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가장 최근 기록을 불러옵니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteMsg_Load {
            get {
                return ResourceManager.GetString("DeleteMsg_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제할 데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteMsg_NoData {
            get {
                return ResourceManager.GetString("DeleteMsg_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공적으로 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteMsg_Success {
            get {
                return ResourceManager.GetString("DeleteMsg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteMsgCaption {
            get {
                return ResourceManager.GetString("DeleteMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditData_Caption {
            get {
                return ResourceManager.GetString("EditData_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditData_Success {
            get {
                return ResourceManager.GetString("EditData_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정 내용을 적용하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditDataMsg {
            get {
                return ResourceManager.GetString("EditDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   교체할 데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditLoadMsg {
            get {
                return ResourceManager.GetString("EditLoadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   파일 저장 중 오류가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Err_Saving {
            get {
                return ResourceManager.GetString("Err_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류 발생과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrMsg_Caption {
            get {
                return ResourceManager.GetString("ErrMsg_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유량평균 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlowAvg1Caption {
            get {
                return ResourceManager.GetString("FlowAvg1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유량평균 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlowAvg2Caption {
            get {
                return ResourceManager.GetString("FlowAvg2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀 파일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Load_type {
            get {
                return ResourceManager.GetString("Load_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀 로드 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadExcel_Err {
            get {
                return ResourceManager.GetString("LoadExcel_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀 파일을 닫으신 후에 다시 시도해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadExcel_ExistErr {
            get {
                return ResourceManager.GetString("LoadExcel_ExistErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 로드 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadingDataMsg {
            get {
                return ResourceManager.GetString("LoadingDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_Saved {
            get {
                return ResourceManager.GetString("Msg_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF로 저장 중…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Msg_SavingPdf {
            get {
                return ResourceManager.GetString("Msg_SavingPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경 사항이 저장되지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewLoadMsg1 {
            get {
                return ResourceManager.GetString("NewLoadMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계속하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewLoadMsg2 {
            get {
                return ResourceManager.GetString("NewLoadMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주입기록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PDF_Caption {
            get {
                return ResourceManager.GetString("PDF_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압력평균 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PressAvg1Caption {
            get {
                return ResourceManager.GetString("PressAvg1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압력평균 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PressAvg2Caption {
            get {
                return ResourceManager.GetString("PressAvg2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제작사 http://www.wooribnc.com 우리비엔씨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProducerMsg {
            get {
                return ResourceManager.GetString("ProducerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QuitMsg {
            get {
                return ResourceManager.GetString("QuitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QuitMsg_Caption {
            get {
                return ResourceManager.GetString("QuitMsg_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   신규등록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string regist_text {
            get {
                return ResourceManager.GetString("regist_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   교체할 데이터가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReplaceLoadMsg {
            get {
                return ResourceManager.GetString("ReplaceLoadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveMsg {
            get {
                return ResourceManager.GetString("SaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveMsg_Caption {
            get {
                return ResourceManager.GetString("SaveMsg_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveMsg_Success {
            get {
                return ResourceManager.GetString("SaveMsg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 저장 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SavingMsg {
            get {
                return ResourceManager.GetString("SavingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회 결과 - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchResult1 {
            get {
                return ResourceManager.GetString("SearchResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   건과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchResult2 {
            get {
                return ResourceManager.GetString("SearchResult2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유량 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Series0 {
            get {
                return ResourceManager.GetString("Series0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압력 1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Series1 {
            get {
                return ResourceManager.GetString("Series1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유량 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Series2 {
            get {
                return ResourceManager.GetString("Series2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압력 2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Series3 {
            get {
                return ResourceManager.GetString("Series3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataBase 와의 연결에 문제가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Splash_DB_Err {
            get {
                return ResourceManager.GetString("Splash_DB_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   우성엔지니어링과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string toggleFloat {
            get {
                return ResourceManager.GetString("toggleFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string toggleInt {
            get {
                return ResourceManager.GetString("toggleInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   공백 또는 0 입력 시 초기값으로 적용됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tooltip {
            get {
                return ResourceManager.GetString("tooltip", resourceCulture);
            }
        }
    }
}
